# #### PayFlow Kubernetes Namespace ####
# #### This creates a separate namespace for all PayFlow resources ####
# #### Namespaces provide isolation and organization in Kubernetes ####

apiVersion: v1  # #### Kubernetes API version ####
kind: Namespace  # #### Resource type - creates a namespace ####
metadata:
  name: payflow  # #### Namespace name - all PayFlow resources will be in this namespace ####

