apiVersion: v1
kind: Secret
metadata:
  name: payflow-secrets
  namespace: payflow
type: Opaque
stringData:
  # Database Credentials
  DB_USER: "payflow"
  DB_PASSWORD: "payflow123"
  POSTGRES_PASSWORD: "payflow123" # Needed for the Postgres Image itself
  
  # Connection Strings (Sensitive because they contain passwords)
  # Note: connecting to 'postgres-service' and 'rabbitmq-service'
  DATABASE_URL: "postgresql://payflow:payflow123@postgres-service:5432/payflow"
  RABBITMQ_URL: "amqp://payflow:payflow123@rabbitmq-service:5672"
  
  # Other Secrets
  RABBITMQ_USER: "payflow"
  RABBITMQ_PASSWORD: "payflow123"
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-k8s-version"
  SMTP_USER: "your_email@gmail.com"
  SMTP_PASS: "your_app_password"